---
- name: Installation SQL Server Tools sur Linux (ubuntu 16.04)
  hosts: all
  become: yes
  
  tasks:
  - name: Import de la cle GPG
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: installation du repo mssql-server-tools
    get_url:
      url: https://packages.microsoft.com/config/ubuntu/16.04/prod.list
      dest: /etc/apt/sources.list.d/msprod.list

  - name: refresh du cache apt-get plus upgrade
    apt:            
      update_cache: yes
      upgrade: dist
      force_apt_get: yes
      
  - name: installation du package mssql-tools & unixodbc-dev
    apt:
      pkg:
       - mssql-tools
       - unixodbc-dev
      state: latest
      force_apt_get: yes
    environment:
      ACCEPT_EULA: 'y'
  
  - name: faire que sqlcmd/bcp soit accessible dans le shell
    lineinfile:
      path: .bashrc
      line: export PATH="$PATH:/opt/mssql-tools/bin"
  
  - name: Source Bashrc
    shell: source ~/.bashrc executable=/bin/bash      
...
