---
- name : "installation du subnet front"
  azure_rm_subnet:
    name: "{{ subnetfe_name }}"
    virtual_network_name: "{{ vnet_name }}"
    resource_group: "{{ rg_name }}"
    address_prefix_cidr: "{{ address_prefix_cidr_subnetfe }}"

...