---
- name: installation du repo mssql-server-tools
  become: yes
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/16.04/prod.list
    dest: /etc/apt/sources.list.d/msprod.list

- name: refresh du cache apt-get plus upgrade
  become: yes
  apt:            
    update_cache: yes
    upgrade: dist
    force_apt_get: yes    

- name: installation du package mssql-tools & unixodbc-dev
  become: yes
  apt:
    pkg:
      - mssql-tools
      - unixodbc-dev
    state: latest
    force_apt_get: yes
  environment:
    ACCEPT_EULA: 'y'

- name: faire que sqlcmd/bcp soit accessible dans le shell
  become: yes
  lineinfile:
    path: .bashrc
    line: export PATH="$PATH:/opt/mssql-tools/bin"
  
- name: Source Bashrc
  become: yes
  shell: source ~/.bashrc executable=/bin/bash   
...