---
- name: php reload
  become: yes    
  service: name=php7.0-fpm
           enabled=yes
           state=restarted

- name: nginx reload
  become: yes
  service: name=nginx
           enabled=yes
           state=restarted
...