---
- name: Installation de bibilothèques pour MS SQL, protocole et outils d'installation
  become: yes
  apt:
    pkg:
      - freetds-dev
      - freetds-bin
      - python-dev
      - python-pip
    state: latest
    force_apt_get: yes

- name: Installation de pymssql
  become: yes
  pip:
    name: pymssql

- name: creation de la base
  become: yes
  mssql_db:
    name: "{{ db_name }}"
    state: present
    login_host: 127.0.0.1
    login_user: sa
    login_password: "{{ sa_password }}"
...    