---
- name: Delete le fichier index de base
  become: yes
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: Uplaod des fichiers du site
  become: yes
  copy: 
    src: ./SiteWeb/
    dest: /var/www/html/
  notify:
    - start nginx
...